### ISSUE TITLE
Первая итерация ревью

### ISSUE THREAD

**Issue by akhtyamovpavel** [KayumovRu/YobitTracker#1]
Приветствую!

Посмотрел код - в целом, получилось неплохо. Но над следующими моментами стоит поработать:

- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L16-L17 - перемешаны функции и код - лучше так не делать. Если необходим timestamp, то лучше объявлять его в классе
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L20-L27 - лучше вынести в отдельную функцию, после чего ее вызвать в конце файла
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L22 - у меня не запустится такой код - лучше использовать `os.path.join` для поддержки кроссплатформенности
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L44 - лучше кидать исключение, а не делать выход через `sys.exit`, а в другом месте ловить это исключение
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L62-L84 - выносим в сущность `if __name__ == '__main__'`
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/1_dataupdate.py#L83 - путь к базе данных лучше задать через константу, чтобы можно было использовать в других модулях
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/2_chartcreate.py#L16 - лучше назвать функцию `draw_balance`
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/2_chartcreate.py#L39 - `os.path.join`
- [ ] https://github.com/KayumovRu/YobitTracker/blob/master/2_chartcreate.py#L50-L170 - этот код стоит разбить на функции, которые приблизительно логически разбиваются. И дополнительно стоит вынести вызовы этих функций в `__main__`
- [ ] Дополнительно стоит разбить файл на модули, где функции объединены логикой. После этого можно будет сделать красивые импорты

Буду ждать новую версию!

**Comment by KayumovRu** [comment]
Павел, спасибо за комментарии! Забыл тут отреагировать. А глядя на дату, даже вспомнил, почему забыл -_-

Все замечания изучил. Добавлю только, что далее пет вылился в продолжение в виде бота для учебного проекта в следующий реп - https://github.com/KayumovRu/CryptoIndiBot 
За сим тут закрываю. Далее использую в качестве кейса-примера у себя в работе с учетом твоих замечаний.
